version: '3.4'
services:
  basicwebapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache-basic-webapp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - "8080:80"
